# Generated by Django 3.0.5 on 2020-04-05 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefactor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
