# Generated by Django 3.0.5 on 2020-04-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefactor', '0002_auto_20200405_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benefactor',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
