# Generated by Django 3.0.5 on 2020-04-05 21:42

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('benefactor', '0003_auto_20200405_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='image',
            field=models.ImageField(default='default.img', upload_to=utils.helpers.upload_image),
        ),
    ]
