# Generated by Django 3.0.5 on 2020-04-05 22:20

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('benefactor', '0004_auto_20200406_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='image',
            field=models.ImageField(default='default_benefactor_image.jpg', upload_to=utils.helpers.upload_image),
        ),
    ]
