# Generated by Django 3.0.5 on 2020-04-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_auto_20200406_0312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'Beneficiaries'},
        ),
    ]
