# Generated by Django 3.0.5 on 2020-04-11 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0003_auto_20200406_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='image_date',
            field=models.DateField(help_text='Image clicked date'),
            preserve_default=False,
        ),
    ]
